FROM node:lts-alpine

# Args
ARG DOCKER_USER=angular
ARG VERSION=1.0.0

# Labels
LABEL maintainer="Carlos Abreu <shunwar500@gmail.com>" \
    org.opencontainers.image.authors="Carlos Abreu <shunwar500@gmail.com>" \
    org.opencontainers.image.version="${VERSION}" \
    org.opencontainers.image.title="Angular Docker" \
    org.opencontainers.image.docker_user=${DOCKER_USER}

RUN  apk update && \
apk  no-cache upgrade &&\
    apk add --no-cache --virtual .gyp python make g++ git \
        bash \
        openssl \
        git \
        bash \
        curl \
        chromium && \
	npm install -g bower && \
	npm install -g yuidocjs && \
	npm install -g @angular/cli

WORKDIR /home

RUN git clone http://oauth2:vwpqftyfFSgPx5wAH-mN@git.sigis.com.ve/librerias-desarrollo/angular-template.git &&\
	mv angular-template template &&\
	cd template &&\
	adduser -D ${DOCKER_USER}

USER ${DOCKER_USER}

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/

EXPOSE 9222

WORKDIR /home/${DOCKER_USER}
